package:
  name: deblur
  version: "1.1.0"

source:
  git_url: https://github.com/biocore/deblur.git
  git_rev: 1.1.0

build:
  number: 1

requirements:
  build:
    - python
    - biom-format
    - setuptools
    - numpy<1.14.0
    - scikit-bio >=0.5.0
    - vsearch ==2.7.0
    - mafft ==7.221
    - sortmerna ==2.0
    - biom-format
    - h5py
    - click

  run:
    - python
    - biom-format
    - setuptools
    - numpy<1.14.0
    - scikit-bio >=0.5.0
    - vsearch ==2.7.0
    - mafft ==7.310
    - sortmerna ==2.0
    - biom-format
    - h5py
    - click

test:
  imports:
    - deblur
  commands:
    - deblur --help
about:
  home: https://github.com/biocore/deblur
  license: BSD license
